<?php echo get_header(); ?>
<div class="contactfloat global-width">
    <a href="<?php echo get_home_url() ?>">
        <section>
            <h2><img src="<?php echo OMNI_IMG . "/omni-logo2.svg" ?>" alt=""></h2>
            <p>Contact Us</p>
        </section>
    </a>
</div>
<main class="offer-main global-width">
    <div class="navbar">
        <section>
            <div class="header-menu">
                <h1><a href="<?php echo get_home_url() . "/home" ?>"><img
                            src="<?php echo OMNI_IMG . "/Omniverse-logo.svg" ?>" alt="omniverse"></a></h1>
                <a class="close menunav">
                    <span></span>
                    <span></span>
                </a>
            </div>
            <nav>

                <ul>
                    <li><a href="<?php echo get_home_url() . "/home" ?>">Home</a></li>
                    <li><a href="<?php echo get_home_url() . "/about" ?>">Who We Are</a></li>
                    <li><a href="<?php echo get_home_url() . "/offer" ?>">What we offer</a></li>
                    <li><a href="<?php echo get_home_url() . "/blogs" ?>">Updates</a></li>
                    <li><a href="<?php echo get_home_url() . "/contact" ?>">Contact</a></li>

                </ul>
            </nav>
        </section>
    </div>
    <div class="about1 offer">
        <img src="<?php echo OMNI_IMG . "/bg_eerg.png" ?>" alt="">
        <section>
            <h2>THE TECHNOLOGY</h2>
            <p>The Electromagnetic Energy-Flux Reactor</p>
        </section>
    </div>

    <div class="offer2">
        <section>
            <h2>Guiding Principles</h2>
            <p>The main principle underpinning the Electromagnetic Energy-Flux Reactor’s (EER) operation is <span>

                    Faraday’s Law of Induction which stipulates “that when a coil is or coils of wire are exposed to
                    varying magnetic fields, a voltage will be induced into the coils” and by the process of converting
                    the back electromagnetic force as a positive induced emf through electromagnetic induction feedback
                    system by the reactors assembly.
                </span></p>
            <p>Similar to the principles guiding the operation of conventional generators – where a prime mover spins
                the rotors to produce varying magnetic fields at the stator of an alternating generator – EER simulates
                the same effect without the need for a rotating magnetic field, making use of electromagnetic induction
                feedback to contract and expand the magnetic fields in the main reactor, by making use of a network of
                reactors and transformers through as <span>patented regenerative electromagnetic induction feedback
                    system thereby converting the back emf generated by the loads into usable positive electromagnetic
                    feedback emf.
                </span></p>
        </section>
    </div>
    <div class="offer3">
        <section>
            <h2>Stationary Power Generation Application</h2>
            <p>EER stationary power generation (EER-SPG) systems are scalable, portable, have minimal moving parts, do
                not make use of fossil fuels as input and do not emit harmful wastes or emissions to the environment.
                More significantly, EER can provide stable electricity supply on a 24/7 basis at a higher capacity
                factor than current market alternatives and can easily operate in various locations due to its modular
                configuration and small physical footprint of < 10 m2/MW. The EER has also been designed to be stackable
                    vertically to maximize the usage of space. Large capacity output can be attained by having the units
                    connected in parallel, capable of operating seamlessly On-Grid and Off-Grid. Shorter lead time to
                    implement and operate, like for example from contract signing, a 300MW capacity output can be
                    delivered and installed within six (6) months. </p>
                    <p>To better understand how EER operates, it is worth revisiting the mechanisms behind the operation
                        of conventional generators, which illustrate how both the latter and the EER produce the same
                        varying magnetic fields to generate electricity in compliance with Faraday’s Law of Induction.
                    </p>
        </section>
    </div>
    <div class="offer4">
        <section>
            <h2>Conventional Methods of Power Generation</h2>
            <p>A brief description of the parts of a conventional generator and how they deliver varying magnetic fields
                on
                the stator core and windings are outlined below:</p>
            <table>
                <tr>
                    <th>COMPONENT</th>
                    <th>PURPOSE</th>
                </tr>
                <tr>
                    <td>Prime Mover</td>
                    <td>Responsible for the rotation of the main rotor and exciter rotor</td>
                </tr>
                <tr>
                    <td>Alternator</td>
                    <td>Composed of a stator (stationary part) and a rotor (rotating part)</td>
                </tr>
                <tr>
                    <td>Exciter</td>
                    <td>Composed of a stator (stationary part) and a rotor (rotating part)</td>
                </tr>

            </table>
        </section>
    </div>
    <div class="techfeature">
        <div class="framer">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/pq8ouKgTagU?si=jB5wvy79ZpmNhn2A"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowfullscreen></iframe>
            <section>
                <h2>Main Features</h2>
                <p>The EER-SPG device, as designed, has the following features which distinguishes itself from existing
                    renewable and conventional sources of power and energy</p>
            </section>
        </div>
        <div class="features">
            <ul>
                <li>Produces electricity on demand-without availability constraints associated with hydro, wind and
                    solar power and other renewable energy supply</li>
                <li>Seamless on-grid off-grid operation - power generation can be switched from isolated loads to
                    utility network load instantaneously without the need for shutdown</li>
                <li>Quick start-up and shutdown - less than 60 second depending converter controls and load or network
                    conditions</li>
                <li>Black start-up capability - through local power supply, UPS, battery bank, small wind or solar power
                    installation</li>
                <li>Compensated parasitic load - the gross output is design to compensate, supply and offset the
                    internal losses of the device</li>
                <li>No inherent pollution - no green gas emission whatsoever</li>
                <li>Compact and portable - footprint is < 10 m2 and a height of 2.6 m</li>
                <li>Rapid mobilization - can be packaged to fit a 20-foot container to facilitate shipment and
                    installation.</li>
                <li>No special conditions for location, installation and operation, have no site-specific environmental
                    constraints</li>
                <li>Scalable to larger capacity, ability to operate in parallel with multiple units in parallel and
                    controlled individually or as a group</li>
            </ul>
        </div>
    </div>

</main>
<?php echo get_footer(); ?>